### ISSUE TITLE
Schnee

### ISSUE THREAD

**Issue by endoanaconda** [chrigu/schifftszbaern#1]
super idee, gfaut mer ächt was du da zmämegschueschteret hesch.
öppis fäut aber: wenn d temperatur z bärn uger 0 grad isch, de schneids.

**Comment by chrigu** [comment]
merci, das wär eigentlich scho dinne u s'radar bild sött o richtig interpretiert wärde. We me aber vergisst vor de Ferie s'ganze ufem Raspberry z'deploye, de isch hopfe u malz verlore. Aber teschte muess is no :)

**Comment by chrigu** [comment]
Voilà: https://twitter.com/schifftszbaern/status/556439616442859520
